/*
-- Query: SELECT * FROM pdev_game_w_authentication.authorities
LIMIT 0, 1000

-- Date: 2018-06-11 09:10
*/
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('AUTHORITY_MENU_CONTROL','authentication.AUTHORITY_MENU_CONTROL','AUTHULITY','W-ADMIN','메뉴를 변경합니다.','/bluedog/authority/menu/list','/bluedog/authority/menu/**',23,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('AUTHULITY','authentication.AUTHULITY',NULL,'W-ADMIN','권한(메뉴 권한)',NULL,NULL,22,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('AUTHULITY_GROUP_MANAGE','authentication.authentication.AUTHORITY_MENU_CONTROL','AUTHULITY','W-ADMIN','권한 구룹 관리(권한 구룹을 관리 할 수 있습니다.)','/bluedog/authority/management/list','/bluedog/authority/management/**',24,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('AUTHULITY_USER_MANAGE','authentication.authentication.AUTHULITY_USER_MANAGE','AUTHULITY','W-ADMIN','담당자 권한관리(운영툴 사용자의 권한을 추가 하거나 삭제 할 수 있습니다.)','/bluedog/authority/person/management/list','/bluedog/authority/person/management/**',25,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('BATTLE','authentication.BATTLE',NULL,'W-ADMIN','컨텐트 관리',NULL,NULL,7,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('BATTLE_FILEDBATTLE','authentication.BATTLE_FILEDBATTLE','BATTLE','W-ADMIN','컨텐츠 관리 (전장을 관리 할 수 있습니다.)','/battleField/list','/battleField/**',8,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('CONNECTION_CONTEXT','authentication.CONNECTION_CONTEXT',NULL,'W-ADMIN','연결 설정 (DB, PDL 추가 설정)',NULL,NULL,20,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('CONNECTION_CONTEXT_SETTING','authentication.CONNECTION_CONTEXT_SETTING','CONNECTION_CONTEXT','W-ADMIN','설정 (게임서버 추가 시 게임 DB 및 PDL 연결 설정을 추가로 할 수 있습니다.)','/connection/setting/list','/connection/setting/**',21,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('CONNECTION_STATE_LIST','authentication.authentication.CONNECTION_STATE_LIST','CONNECTION_CONTEXT','W-ADMIN','상태(디비 및 각종 연결 상태를 확인 할 수 있습니다.)','/connection/state/list','/connection/state/**',27,'Y','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('DASHBOARD','authentication.DASHBOARD',NULL,'W-ADMIN','대시보드','/dashboard/view','/dashboard/**',0,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('GAME','authentication.GAME',NULL,'W-ADMIN','게임 메뉴',NULL,NULL,1,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('GAME_BULK_MAIL','authentication.GAME_BULK_MAIL','GAME','W-ADMIN','아이템을 첨부하여 우편을 보낼수 있습니다.','/mailBox/index','/mailBox/**',6,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('GAME_CHARACTER_MANAGE','authentication.GAME_CHARACTER_MANAGE','GAME','W-ADMIN','캐릭터에 대한 상세 정보를 볼 수 있습니다.','/gameCharacter/list','/gameCharacter/**',2,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('GAME_ITEM_LIST','authentication.GAME_ITEM_LIST','GAME','W-ADMIN','아이템(캐릭터들이 가지고 있는 아이템을 조회 할 수 있습니다.)','/gameItem/list','/gameItem/**',3,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('GAME_MAILBOX_HISTORY','authentication.GAME_MAILBOX_HISTORY','GAME','W-ADMIN','우편히스토리 (우편 발송한 히스토리를 볼 수 있습니다.)','/userMailboxHistory/list','/userMailboxHistory/**',4,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('GAME_NOTICE_INFO','authentication.GAME_NOTICE_INFO','GAME','W-ADMIN','공지 (게임 내의 공지 사항을 보낼 수 있습니다.)','/noticeInfo/list','/noticeInfo/**',5,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('LOG','authentication.LOG',NULL,'W-ADMIN','로그',NULL,NULL,17,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('LOG_CHAT_LOG','authentication.LOG_CHAT_LOG','LOG','W-ADMIN','채팅 로그(게임의 채팅 로그를 조회 할 수 있습니다.)','/chatlog/list','/chatlog/**',18,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('LOG_USER_LOG','authentication.LOG_USER_LOG','LOG','W-ADMIN','유저 로그를 조회 할 수 있습니다.','/userLog/list','/userLog/**',19,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('MONITORING','authentication.MONITORING',NULL,'W-ADMIN','모니터링',NULL,NULL,9,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('MONITORING_CONCURRENT_USER','authentication.MONITORING_CONCURRENT_USER','MONITORING','W-ADMIN','유저 동접 수치를 볼 수 있습니다.','/concurrentUserMonitoring/realtime/concurrentuser/list','/concurrentUserMonitoring/realtime/concurrentuser/**',10,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('MONITORING_SERVER_STATUS','authentication.MONITORING_SERVER_STATUS','MONITORING','W-ADMIN','서버 접속 현황 (게임 서버의 상태를 확인 할 수 있습니다.)','/serverStatusMonitoring/list','/serverStatusMonitoring/**',11,'N','Y','Y','fa-desktop');
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('TEST','TEST name1',NULL,'W-ADMIN','DB 설정',NULL,NULL,28,'N','Y','Y',NULL);
INSERT INTO `authorities` (`id`,`name`,`parent_id`,`category`,`description`,`url`,`url_pattern`,`sort_order`,`has_game_yn`,`use_yn`,`show_yn`,`icon`) VALUES ('TOOL_USER_LOG','authentication.authentication.TOOL_USER_LOG','MONITORING','W-ADMIN','활동 로그(운영툴의 사용의 로그를 조회 할 수 있습니다.)','/userAction/search','/userAction/**',26,'N','Y','Y','fa-desktop');